Add gallery for Join Us page
ubc-biomod/biomod-website pull request #11
Opened 2024-06-28 05:41 UTC by daniel-panhead

2024-07-14 15:53 UTC, IcedTea2K requested changes

2024-07-14 15:53 UTC, IcedTea2K commented on src/components/join-us/TeamsGallery.tsx
I like the animation a lot. But the size between each card is different, making the arrow move around. It's hard to go through the entire thing without moving the mouse
<img width="459" alt="image" src="https://github.com/user-attachments/assets/b4c37d94-3976-47d1-87a1-56b4627180de">
<img width="502" alt="image" src="https://github.com/user-attachments/assets/c903105e-73c6-4685-9ee0-a07c48e98c14">

2024-07-16 06:47 UTC, daniel-panhead commented on src/components/join-us/TeamsGallery.tsx
I resolved by making the image ratio fixed, with the assumption that all the images once we populate will be the same ratio

2024-07-20 02:36 UTC, IcedTea2K approved these changes
LGTM

2024-07-20 02:46 UTC, merged