[Support Us Page] [Populated] Help Our Team Section
ubc-biomod/biomod-website pull request #12
Opened 2024-07-12 08:13 UTC by daniel-panhead

![image](https://github.com/user-attachments/assets/d16ac36d-e7e1-4398-b68f-154a7bbfabf4)

Yay cards

2024-07-14 15:45 UTC, IcedTea2K requested changes
Very nice overall. Just a few small things on mobile version.

2024-07-14 15:45 UTC, IcedTea2K commented on src/components/support-us/Card.tsx
Is it intended to have white space between description and link for no-image cards on mobile?
<img width="312" alt="image" src="https://github.com/user-attachments/assets/72728e94-53cd-4e16-9877-ac263ef9a4fa">

2024-07-16 06:24 UTC, daniel-panhead commented on src/components/support-us/Card.tsx
No :) Fixed now

2024-07-20 02:29 UTC, IcedTea2K approved these changes
LGTM!

2024-07-20 02:32 UTC, merged