Add about us hero
ubc-biomod/biomod-website pull request #13
Opened 2024-07-12 08:32 UTC by daniel-panhead

![image](https://github.com/user-attachments/assets/50658ba0-63d9-4952-b471-d6f505ccfe40)

![image](https://github.com/user-attachments/assets/ab80f404-9f50-41d9-b35a-444701ba5ded)

2024-07-14 15:38 UTC, IcedTea2K requested changes
LGTM! Just one-line nitpick

2024-07-14 15:38 UTC, IcedTea2K commented on src/components/about-us/Hero.tsx
> +import Image from "next/image";
```suggestion
```

2024-07-16 06:24 UTC, daniel-panhead commented on src/components/about-us/Hero.tsx
> +import Image from "next/image";
Woooah u can suggest changes??

2024-07-20 02:26 UTC, IcedTea2K approved these changes
LGTM

2024-07-20 02:31 UTC, merged